languageCode = "en-us"
title = "Prologue"
baseurl = "https://vitr.github.io/vvitr.com"
theme = "prologue"
#https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

[params]
  name = "Jane Doe"
  description = "Hyperspace Engineer"
  copyright = "Untitled."
  email = "vit@vvitr.com"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[[params.social]]
  medium = "dribbble"
  icon = "dribbble"
  link = "#"

[[params.social]]
  medium = "email"
  icon = "envelope"
  link = "#"

# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
