languageCode = "en-us"
title = "Vitaliy Ryepnoy - Software Engineer"
baseurl = "https://vvitr.com"
theme = "prologue"
#https://discourse.gohugo.io/t/issue-when-baseurl-have-subdirectory/4088/7
RelativeURLs=true
CanonifyURLs=true

[params]
  name = "Vitaliy Ryepnoy"
  description = "Software Engineer"
  copyright = "2016-2018 Vitaliy Ryepnoy ABN 29 901 015 152"
  email = "vit@vvitr.com"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/_vitr_"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "https://www.facebook.com/vitaliy.ryepnoy"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/vitr"

[[params.social]]
  medium = "stack-overflow"
  icon = "stack-overflow"
  link = "https://stackoverflow.com/users/4986182/vitr?tab=profile"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/vitaliyr"

[[params.social]]
  medium = "telegram"
  icon = "telegram"
  link = "https://t.me/vvitr"


# Portfolio column one

[[params.portfolio1]]
  title = "Ipsum Feugiat"
  alt = ""
  source = "img/pic02.jpg"
  url = "#"

[[params.portfolio1]]
  title = "Rhoncus Semper"
  alt = ""
  source = "img/pic03.jpg"
  url = "#"

# Portfolio column two

[[params.portfolio2]]
  title = "Magna Nullam"
  alt = ""
  source = "img/pic04.jpg"
  url = "#"

[[params.portfolio2]]
  title = "Natoque Vitae"
  alt = ""
  source = "img/pic05.jpg"
  url = "#"

# Portfolio column 3

[[params.portfolio3]]
  title = "Dolor Penatibus"
  alt = ""
  source = "img/pic06.jpg"
  url = "#"

[[params.portfolio3]]
  title = "Orci Convallis"
  alt = ""
  source = "img/pic07.jpg"
  url = "#"
